Loginform/Loginform/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.urls import path #не работает выдает ошибку не правильный синтаксис
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# from django.conf.urls import url
# или импорт url а не path
# url(r'^$', views.home, name='home')
# from . точка значит импортируем из этой же дирректории

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^articles/',include('articles.urls')), # делаем import include и далее берет в articles потом urls
    url(r'^about/$',views.about), # views файл который импортнули .about функция которая во views. # если вызван url about то вызываем функции
    url(r'^$',views.homepage), # homepage. ^ - это старт. $ - это конец. ничего по середине нету. для того что бы перейти на название сайта .ee и все
    # затем делаем файо views.py и там создаем функции для about
]

urlpatterns += staticfiles_urlpatterns()

Loginform/accounts/urls.py
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view,name='signup')
]

Loginform/articles/urls.py
from django.conf.urls import url
from . import views

app_name = 'articles'

urlpatterns = [
    url(r'^$',views.article_list, name="list"), 
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail, name="detail"),
]

Loginform/accounts/models.py
from django.db import models

# Create your models here.

Loginform/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    # add in thumbnail later
    # add in author later
    # char поменьше
    # text текс больше

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'
        # делается что бы были покороче предложения при обзоре

Loginform/Loginform/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('homepage')
    # страницу возвразает и показывает, но вместо этого сделаем рендер с запросом на какой темплейт пойдем, и далее пойдем в settings
    return render(request,'homepage.html')

def about(request):
    #return HttpResponse('about') # возвращаем ретурном то что импортнули, что бы перейти в абоут
    # из views переходим в урлс
    # страницу возвразает и показывает
    return render(request,'about.html')

Loginform/accounts/views.py
from django.shortcuts import render

# Create your views here.
def signup_view(request):
    return render(request,'accounts/signup.html')

Loginform/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse
# Create your views here.
def article_list(request):
    articles=Article.objects.all().order_by('date') # by date новые будут первые
    return render(request,'articles/article_list.html',{'articles':articles}) #ставим словарь {}

def article_detail(request,slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

    

Loginform/accounts/templates/accounts/signup.html
{% extends 'base_layout.html'%}

{% block content%}
<h1>Signup</h1>

{% endblock %}

Loginform/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %} 

Loginform/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content %}
    <h1>Article List</h1>
    <div class="articles">
        {% for article in articles%}
            <div class="article">
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
                <p>{{article.snippet}}</p>
                <p>{{article.date}}</p>
            </div>

        {%endfor%}
    </div>

{% endblock %}

Loginform/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
</head>
<body>
    <h1>About us</h1>
    <p>Contact</p>
</body>
</html>

Loginform/templates/base_layout.html
{%load static from staticfiles%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Article</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="{%static 'style.css'%}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'articles:list' %}">articles</a></h1>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

Loginform/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
</head>
<body>
    <h1>Main page login</h1>
    <p>Welcome</p>
</body>
</html>